# Generated by Django 2.1 on 2018-08-30 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('new', 'Новое обращение'), ('inwork', 'В работе'), ('done', 'Выполнено'), ('refused', 'Отказано')], max_length=200)),
                ('text', models.TextField()),
                ('comment', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
